chore: updated

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,14 +1,28 @@
+
 #!/bin/sh
 
+# Fail immediately on non-zero exit code.
+set -e
+# Fail immediately on non-zero exit code within a pipeline.
+set -o pipefail
+# Fail on undeclared variables.
+set -u
+# Debug, echo every command
+# set -x
+
 BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
 
 cd $BUILD_DIR
 
 if [ -f "static.json" ]
 then
-  echo '       Overwriting existing `static.json`'
+  echo '-----> Override existing `static.json` file'
 fi
 
-echo '{ "root": "other/public/storybook/" }' > static.json
+echo '{ "root": "other/public/storybook",  "clean_urls": true, "routes": { "/**": "index.html" } }' > static.json
 
+echo '-----> Start Storybook build'
 yarn run storybook:build
+echo '-----> Finish Storybook build'
